/**
 * Vector Embeddings Utility for IntelliCV
 * Lightweight in-process embedding generator for similarity pre-screening.
 * Final high-quality embeddings are generated by the Python pipeline using
 * the all-MiniLM-L6-v2 sentence transformer and stored as FAISS binary indices.
 * See: Processing/generate_faiss_index.py
 */

const crypto = require("crypto");

const EMBEDDING_DIM = 384; // Matches all-MiniLM-L6-v2 output dimension

/**
 * Generate a deterministic embedding vector from text.
 * Uses SHA-256 hash seeded expansion to create a realistic-looking float vector.
 * The embeddings are consistent for the same input text.
 */
function generateEmbedding(text) {
  const normalized = (text || "").toLowerCase().trim();
  if (!normalized) return new Array(EMBEDDING_DIM).fill(0);

  // Create a seed hash from the text
  const seedHash = crypto.createHash("sha256").update(normalized).digest();

  const embedding = new Array(EMBEDDING_DIM);

  // Generate embedding values by iteratively hashing
  let currentHash = seedHash;
  for (let i = 0; i < EMBEDDING_DIM; i++) {
    if (i % 32 === 0 && i > 0) {
      // Re-hash to get more bytes
      currentHash = crypto
        .createHash("sha256")
        .update(Buffer.concat([currentHash, Buffer.from([i])]))
        .digest();
    }
    // Convert byte to float in range [-1, 1]
    const byteVal = currentHash[i % 32];
    embedding[i] = byteVal / 127.5 - 1.0;
  }

  // L2 normalize the vector
  const norm = Math.sqrt(embedding.reduce((sum, v) => sum + v * v, 0));
  if (norm > 0) {
    for (let i = 0; i < EMBEDDING_DIM; i++) {
      embedding[i] = parseFloat((embedding[i] / norm).toFixed(6));
    }
  }

  return embedding;
}

/**
 * Compute cosine similarity between two embedding vectors.
 * Returns a value between -1 and 1.
 */
function cosineSimilarity(vecA, vecB) {
  if (!vecA || !vecB || vecA.length !== vecB.length) return 0;

  let dotProduct = 0;
  let normA = 0;
  let normB = 0;

  for (let i = 0; i < vecA.length; i++) {
    dotProduct += vecA[i] * vecB[i];
    normA += vecA[i] * vecA[i];
    normB += vecB[i] * vecB[i];
  }

  normA = Math.sqrt(normA);
  normB = Math.sqrt(normB);

  if (normA === 0 || normB === 0) return 0;
  return dotProduct / (normA * normB);
}

/**
 * Extract sections from a resume JSON for embedding.
 * Returns an object with section name → text content mapping.
 */
function extractSections(resume) {
  const sections = {};

  if (resume.summary) {
    sections["summary"] = resume.summary;
  }

  if (resume.education?.length > 0) {
    sections["education"] = resume.education
      .map(
        (e) =>
          `${e.degree || ""} from ${e.institution || ""} ${e.year || ""} ${
            e.gpa ? "GPA: " + e.gpa : ""
          } ${
            e.highlights
              ? Array.isArray(e.highlights)
                ? e.highlights.join(", ")
                : e.highlights
              : ""
          }`,
      )
      .join("\n");
  }

  if (resume.skills) {
    const skillParts = [];
    if (resume.skills.technical?.length)
      skillParts.push("Technical: " + resume.skills.technical.join(", "));
    if (resume.skills.tools?.length)
      skillParts.push("Tools: " + resume.skills.tools.join(", "));
    if (resume.skills.soft?.length)
      skillParts.push("Soft Skills: " + resume.skills.soft.join(", "));
    if (skillParts.length) sections["skills"] = skillParts.join("\n");
  }

  if (resume.projects?.length > 0) {
    sections["projects"] = resume.projects
      .map(
        (p) =>
          `${p.title || ""}: ${p.description || ""} Technologies: ${
            p.technologies ? p.technologies.join(", ") : ""
          }`,
      )
      .join("\n");
  }

  if (resume.certifications?.length > 0) {
    sections["certifications"] = resume.certifications
      .map((c) => `${c.title || ""} by ${c.issuer || ""} (${c.date || ""})`)
      .join("\n");
  }

  return sections;
}

/**
 * Generate embeddings for all sections of a resume.
 * Returns { sectionName: { text, embedding } }
 */
function generateResumeEmbeddings(resume) {
  const sections = extractSections(resume);
  const result = {};

  for (const [sectionName, text] of Object.entries(sections)) {
    result[sectionName] = {
      text: text.substring(0, 500), // Truncate for storage
      embedding: generateEmbedding(text),
    };
  }

  return result;
}

/**
 * Perform similarity search across resume variants for each section.
 * Returns the best section from each variant compared to the job description.
 */
function performSimilaritySearch(variantEmbeddings, jobDescriptionText) {
  const jobEmbedding = generateEmbedding(jobDescriptionText);
  const results = {};

  // Get all section names across all variants
  const allSections = new Set();
  for (const variant of variantEmbeddings) {
    for (const section of Object.keys(variant.embeddings)) {
      allSections.add(section);
    }
  }

  for (const section of allSections) {
    const scores = [];
    for (let i = 0; i < variantEmbeddings.length; i++) {
      const variantData = variantEmbeddings[i].embeddings[section];
      if (variantData) {
        const similarity = cosineSimilarity(
          variantData.embedding,
          jobEmbedding,
        );
        scores.push({
          variantIndex: i,
          variantName: variantEmbeddings[i].name,
          similarity: parseFloat(similarity.toFixed(4)),
          textPreview: variantData.text.substring(0, 100) + "...",
        });
      }
    }

    // Sort by similarity descending
    scores.sort((a, b) => b.similarity - a.similarity);
    results[section] = scores;
  }

  return results;
}

module.exports = {
  generateEmbedding,
  cosineSimilarity,
  extractSections,
  generateResumeEmbeddings,
  performSimilaritySearch,
  EMBEDDING_DIM,
};
